#ifndef SAVE_RETRIEVE_NVS_H
#define SAVE_RETRIEVE_NVS_H

#include "nvs_flash.h"

#define SAVE_PROVISION_TAG          "SAVING PROVISIONING CONFIGs"
#define RETRIEVE_PROVISION_TAG      "RETRIEVING PROVISIONING CONFIGs"
#define SAVE_APP_KEYS_TAG           "SAVING APP_KEYS CONFIGs"
#define RETRIEVE_APP_KEYS_TAG       "RETRIEVING APP_KEYS CONFIGs"
#define SAVE_KEY_BINDINGS_TAG       "SAVING KEY_BINDING CONFIGs"
#define RETRIEVE_KEY_BINDINGS_TAG   "RETRIEVING KEY_BINDING CONFIGs"
#define SAVE_BT_TAG                 "SAVING BT CONFIGs"
#define RETRIEVE_BT_TAG             "RETRIEVING BT CONFIGs"


#endif //SAVE_RETRIEVE_NVS_H